name: Tweet Every 3 Days

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot randomly every 3 days
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        run: |
          python -c "import os, random, datetime; from subprocess import run; \
now = datetime.datetime.utcnow(); \
key = '.last_tweet'; \
should_run = True; \
if os.path.exists(key): \
    with open(key) as f: \
        last = datetime.datetime.fromisoformat(f.read().strip()); \
        delta = (now - last).days; \
        should_run = delta >= 3; \
if should_run: \
    if random.randint(0, 23) == now.hour: \
        run(['python', 'kwfl_bot.py']); \
        with open(key, 'w') as f: \
            f.write(now.isoformat())"
